modules/user/controllers/UnreadNoticeController.php
<?php

namespace app\modules\user\controllers;

use Yii;
use app\models\UnreadNotice;
use yii\filters\VerbFilter;

class UnreadNoticeController extends \app\components\Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {        
        $pages = new \yii\data\Pagination(['totalCount' => UnreadNotice::ApiNoticesUserCount(Yii::$app->user->id), 'pageSize' => Yii::$app->params['default_Pagination_PageSize']]);
        
        $data = UnreadNotice::ApiNoticesUser(Yii::$app->user->id, false, $pages->pageSize, $pages->offset);
        
        $dataProvider = new \yii\data\ArrayDataProvider([
            'models' => $data['notices'],
            'pagination' => $pages,
            'totalCount' => $pages->totalCount
        ]);

        return $this->render('index', [
            'data' => $data,
            'pages' => $pages,
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionDelete()
    {
        $this->jsonResponse();
        
        $dellistids = Yii::$app->request->post('dellistids');
        
        if(UnreadNotice::deleteAll(['in', 'id_notice', $dellistids])){            
            return [
                'success' => true,
            ];
        }
        return [
            'success' => false,
        ];
    }
}

modules/user/views/unread-notice/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\modelsView\ViewUnreadNotice;

$this->title = Yii::t('app', 'Notifications Archive');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="unread-notice-index">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <?= Html::button(Yii::t('app', 'Delete Selected'), ['id' => 'btn-check', 'class' => 'btn btn-danger']); ?>
    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => Yii::t('app', 'Text notify'),
                'value' => function ($model, $key, $index, $column) {
                    return ViewUnreadNotice::newHtmlNotify($model);
                },
                'format' => 'raw',                
            ],
            ['class' => 'yii\grid\CheckboxColumn'],
        ],
        'pager' => [
           'class' => \kop\y2sp\ScrollPager::className(),
           'container' => '.grid-view tbody',
           'item' => 'tr',
           'paginationSelector' => '.grid-view .pagination',
           'triggerTemplate' => '<tr class="ias-trigger"><td colspan="100%" style="text-align: center"><a style="cursor: pointer">{text}</a></td></tr>',
        ],
    ]); ?>
    
    <?php //переделать
    $script = '
    jQuery(document).ready(function() {
      $("#btn-check").click(function() {
        var keys = $("#w0").yiiGridView("getSelectedRows");
        $.ajax({
            type: "POST",
            url: "'.\yii\helpers\Url::to(['unread-notice/delete']).'", 
            dataType: "json",
            data: {dellistids: keys},
            success: function(response){
                if(response.success){
                    $.each( keys, function( index, value ) {
                        $("tr[data-key="+value+"]").remove();
                    });
                } else {
                    alert("Ошибка удаления или сущность уже удалена");
                }
            },
            beforeSend: function(){
                if(keys == "") return false;
                if(!confirm("Точно удалить?")) return false;                
            }
        });
      });
    });';
    $this->registerJs($script, \yii\web\View::POS_END);
    ?>
</div>